In [23]:
import pandas as pd
data = pd.read_csv('C:\\Users\\raja.a.muthuraman\\Downloads\\DS\\Multiple Regression\\Restaurant_Profit_Data.csv')
data

Miscellaneous_Expenses  Food_Innovation_Spend  Advertising     City  \
0                138671.80              167497.20    475918.10  Chicago   
1                153151.59              164745.70    448032.53   Mumbai   
2                102919.55              155589.51    412068.54    Tokyo   
3                120445.85              146520.41    387333.62  Chicago   
4                 93165.77              144255.34    370302.42    Tokyo   
5                101588.71              134024.90    366995.36  Chicago   
6                148972.87              136763.46    131850.82   Mumbai   
7                147304.06              132446.13    328010.68    Tokyo   
8                150492.95              122690.52    315747.29  Chicago   
9                110453.17              125482.88    309115.62   Mumbai   
10               112368.11              104061.08    233294.95    Tokyo   
11                93564.61              102819.96    253878.55   Mumbai   
12               129094.38               96011.75    253973.44    Tokyo   
13               137269.07               94140.39    256798.93   Mumbai   
14               158321.42              122091.24    260646.92    Tokyo   
15               124390.84              116671.61    265910.23  Chicago   
16               123371.55               80161.11    268480.06   Mumbai   
17               146851.58               96805.16    286708.31  Chicago   
18               115949.79               93897.16    299053.57    Tokyo   
19               155288.11               88567.70      4134.00  Chicago   
20               115641.30               78401.86    302798.47   Mumbai   
21               155547.43               80537.47    303871.29  Chicago   
22               124556.75               76142.56    307453.26    Tokyo   
23               107525.03               69680.53    308902.73    Tokyo   
24               101055.34               79192.01    144708.81  Chicago   
25               141327.16               66812.71    142096.62   Mumbai   
26               145909.98               77476.87    138184.07    Tokyo   
27               129638.55               74255.60    357317.81  Chicago   
28               184419.56               68199.52    122282.20    Tokyo   
29               154806.06               67753.48    111272.38  Chicago   
30               117415.28               64142.48     95265.24    Tokyo   
31               154475.92               63284.38     92352.23  Chicago   
32               130993.61               65556.86     50219.25   Mumbai   
33               104831.49               57641.95    218768.81    Tokyo   
34               159467.92               48574.07    214931.67   Mumbai   
35                86821.44               48162.02    209651.64  Chicago   
36               128830.21               30811.76    205260.82    Tokyo   
37                53057.14               46217.95    201163.42   Mumbai   
38                67721.93               22377.59    189399.10  Chicago   
39                84756.09               40706.51    179133.30   Mumbai   
40               120320.05               30902.33    176929.67   Mumbai   
41                86484.77               30040.92    168604.71    Tokyo   
42                97963.63               25788.93    152135.11   Mumbai   
43               129156.30               17653.73     39668.17  Chicago   
44               156580.14               24325.74     32468.72   Mumbai   
45               125927.04                3148.23      6037.93  Chicago   
46               117590.21                3463.46    301248.46    Tokyo   
47               137200.92                2148.00      4134.00   Mumbai   
48                53517.15                2690.05      4134.00  Chicago   
49               118757.80                2148.00     49307.06   Mumbai   

       Profit  
0   202443.83  
1   201974.06  
2   201232.39  
3   193083.99  
4   176369.94  
5   167173.12  
6   166304.51  
7   165934.60  
8   162393.77  
9   159941.96  
10

In [24]:
data.shape

(50, 5)

In [25]:
ohe=pd.get_dummies(X[:,3])
ohe
data = pd.concat([data.reset_index(drop=True),ohe],axis=1)
data
data = data.drop('City',axis=1)
data

Miscellaneous_Expenses  Food_Innovation_Spend  Advertising     Profit  0  \
0                138671.80              167497.20    475918.10  202443.83  1   
1                153151.59              164745.70    448032.53  201974.06  0   
2                102919.55              155589.51    412068.54  201232.39  0   
3                120445.85              146520.41    387333.62  193083.99  1   
4                 93165.77              144255.34    370302.42  176369.94  0   
5                101588.71              134024.90    366995.36  167173.12  1   
6                148972.87              136763.46    131850.82  166304.51  0   
7                147304.06              132446.13    328010.68  165934.60  0   
8                150492.95              122690.52    315747.29  162393.77  1   
9                110453.17              125482.88    309115.62  159941.96  0   
10               112368.11              104061.08    233294.95  156303.95  0   
11                93564.61              102819.96    253878.55  154441.40  0   
12               129094.38               96011.75    253973.44  151767.52  0   
13               137269.07               94140.39    256798.93  144489.35  0   
14               158321.42              122091.24    260646.92  142784.65  0   
15               124390.84              116671.61    265910.23  140099.04  1   
16               123371.55               80161.11    268480.06  137174.93  0   
17               146851.58               96805.16    286708.31  135552.37  1   
18               115949.79               93897.16    299053.57  134448.90  0   
19               155288.11               88567.70      4134.00  132958.86  1   
20               115641.30               78401.86    302798.47  128656.03  0   
21               155547.43               80537.47    303871.29  121495.02  1   
22               124556.75               76142.56    307453.26  120534.25  0   
23               107525.03               69680.53    308902.73  118915.99  0   
24               101055.34               79192.01    144708.81  118734.04  1   
25               141327.16               66812.71    142096.62  117586.34  0   
26               145909.98               77476.87    138184.07  115915.54  0   
27               129638.55               74255.60    357317.81  115190.31  1   
28               184419.56               68199.52    122282.20  113464.38  0   
29               154806.06               67753.48    111272.38  111186.64  1   
30               117415.28               64142.48     95265.24  110119.59  0   
31               154475.92               63284.38     92352.23  107665.56  1   
32               130993.61               65556.86     50219.25  107609.84  0   
33               104831.49               57641.95    218768.81  106960.92  0   
34               159467.92               48574.07    214931.67  106894.80  0   
35                86821.44               48162.02    209651.64  106661.51  1   
36               128830.21               30811.76    205260.82  100890.19  0   
37                53057.14               46217.95    201163.42  100131.14  0   
38                67721.93               22377.59    189399.10   91411.06  1   
39                84756.09               40706.51    179133.30   91187.76  0   
40               120320.05               30902.33    176929.67   88421.91  0   
41                86484.77               30040.92    168604.71   87980.83  0   
42                97963.63               25788.93    152135.11   81680.49  0   
43               129156.30               17653.73     39668.17   79940.98  1   
44               156580.14               24325.74     32468.72   75382.33  0   
45               125927.04                3148.23      6037.93   75108.08  1   
46               117590.21                3463.46    301248.46   59672.75  0   
47               137200.92                2148.00      4134.00   52741.73  0   
48                53517.15                2690.05      4134.00   45855.41  1   
49  

In [29]:
features = ["Miscellaneous_Expenses","Food_Innovation_Spend","Advertising",0,1,2]
response = ["Profit"]
# X is independent variables
# Y is dependent variable
X=data[features].values
y=data[response].values
X

array([[1.3867180e+05, 1.6749720e+05, 4.7591810e+05, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.5315159e+05, 1.6474570e+05, 4.4803253e+05, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0291955e+05, 1.5558951e+05, 4.1206854e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.2044585e+05, 1.4652041e+05, 3.8733362e+05, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [9.3165770e+04, 1.4425534e+05, 3.7030242e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.0158871e+05, 1.3402490e+05, 3.6699536e+05, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.4897287e+05, 1.3676346e+05, 1.3185082e+05, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.4730406e+05, 1.3244613e+05, 3.2801068e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.5049295e+05, 1.2269052e+05, 3.1574729e+05, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.1045317e+05, 1.2548288e+05,

In [30]:
X = X[:,1:]
X

array([[1.6749720e+05, 4.7591810e+05, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [1.6474570e+05, 4.4803253e+05, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [1.5558951e+05, 4.1206854e+05, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [1.4652041e+05, 3.8733362e+05, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [1.4425534e+05, 3.7030242e+05, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [1.3402490e+05, 3.6699536e+05, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [1.3676346e+05, 1.3185082e+05, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [1.3244613e+05, 3.2801068e+05, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [1.2269052e+05, 3.1574729e+05, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [1.2548288e+05, 3.0911562e+05, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00],
       [1.0406108e+05, 2.3329495e+05, 0.0000000e+00, 0.0000000e+00,
        1.00

In [31]:
#Dividing data in test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

#Importing neccesary packages
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [32]:
#using sklearn method
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(X_train,y_train)
print(reg.coef_)
print(reg.intercept_)

[[ 8.01400884e-01  2.86044604e-02 -4.24252960e+01 -3.62642655e+02
   4.05067951e+02]]
[54493.27600164]


In [53]:
import statsmodels.api as sm
X_with_constant = sm.add_constant(X_train)
model = sm.OLS(y_train, X_with_constant)
results = model.fit()
results.params
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     146.5
Date:                Sat, 03 Sep 2022   Prob (F-statistic):           3.14e-19
Time:                        12:27:08   Log-Likelihood:                -370.20
No. Observations:                  35   AIC:                             750.4
Df Residuals:                      30   BIC:                             758.2
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.087e+04   2643.283     15.462      0.000    3.55e+04    4.63e+04
x1             0.8014      0.054     14.707      0.000       0.690       0.913
x2             0.0286      0.020      1.402      0.171      -0.013       0.070
x3          1.358e+04   2673.085      5.081      0.000    8121.725     1.9e+04
x4          1.326e+04   2344.389      5.656      0.000    8472.795     1.8e+04
x5          1.403e+04   3328.688      4.214      0.000    7230.298    2.08e+04
==============================================================================
Omnibus:                       11.730   Durbin-Watson:                   2.468
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               13.099
Skew:                          -0.970   Prob(JB):                      0.00143
Kurtosis:                       5.285   Cond. No.                     7.17e+21
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.49e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [38]:
# Training score
y_pred = reg.predict(X_train)
df = pd.DataFrame(data = y_train ,columns =['y_test'])
df['y_pred'] = y_pred
df

y_test         y_pred
0   165934.60  170423.358123
1   142784.65  160198.036117
2    75108.08   57146.556740
3    45855.41   56724.909993
4   111186.64  111931.435857
5   140099.04  155557.800740
6   110119.59  109027.194909
7   107609.84  108104.453448
8   137174.93  126051.545009
9    81680.49   79149.647378
10  128656.03  125623.340105
11   79940.98   69733.252131
12  162393.77  161806.922745
13  144489.35  136920.419937
14  117586.34  111738.995342
15  167173.12  172356.228286
16  135552.37  140231.728006
17   88421.91   83956.765668
18   24863.40   57262.444292
19  201974.06  198973.711725
20  151767.52  139107.018484
21  100131.14   96923.910417
22  118734.04  122054.714949
23  166304.51  167504.512643
24  118915.99  119576.378203
25  100890.19   85462.290654
26  121495.02  127685.724642
27  132958.86  125547.334613
28  159941.96  163534.809816
29   91187.76   91876.877833
30   59672.75   66291.013510
31  193083.99  182951.905998
32  202443.83  202296.635299
33   52741.73   55970.293285
34   75382.33   74554.053102

In [39]:
# Test score
from sklearn.metrics import mean_squared_error,r2_score
print('MSE: %.2f' % mean_squared_error(y_train, y_pred))
print('R^2: %.2f' % r2_score(y_train, y_pred))

MSE: 90102423.54
R^2: 0.95


In [35]:
y_predict = reg.predict(X_test)

In [36]:
df = pd.DataFrame(data = y_test ,columns =['y_test'])
df['y_predict'] = y_predict
df

y_test      y_predict
0   113464.38  113051.315915
1   154441.40  143792.699113
2   156303.95  144966.261612
3    87980.83   83796.010549
4   201232.39  191374.913042
5   115190.31  124180.237338
6    91411.06   77801.930172
7   107665.56  107808.694485
8   120534.25  124713.593449
9   176369.94  181097.001859
10  106960.92  107350.417402
11  106661.51   99044.908145
12  115915.54  120941.056816
13  106894.80   99205.940430
14  134448.90  138701.876983

In [37]:
# Test score
from sklearn.metrics import mean_squared_error,r2_score
print('MSE: %.2f' % mean_squared_error(y_test, y_predict))
print('R^2: %.2f' % r2_score(y_test, y_predict))

MSE: 54885162.90
R^2: 0.94


In [51]:
some = [1,0,160349,134321,401400]
import numpy as np
feature_array = np.array(some)
feature_array = feature_array.reshape(1,-1)
print(feature_array)
reg.predict(feature_array)


[[       0        0 15000000   134321   401400]]


array([[-5.22441195e+08]])

In [52]:
round(float(reg.predict(feature_array)),2)

-522441195.17

In [55]:
x = [100000,50000,50,200000]
x1 = np.log(x)
x1

array([11.51292546, 10.81977828,  3.91202301, 12.20607265])

In [56]:
x2 = np.exp(x1)
x2

array([1.e+05, 5.e+04, 5.e+01, 2.e+05])

TypeError: only size-1 arrays can be converted to Python scalars